spring:
  application:
    name: school
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  main:
    banner-mode: off

server:
  port: 8080




